# Generated by Django 5.2 on 2025-04-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_deleted_at_projectinvitation_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('INVITED', 'Invited')], default='ACTIVE', max_length=20),
        ),
    ]
