# Generated by Django 5.2 on 2025-04-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectinvitation',
            unique_together=set(),
        ),
    ]
