# Generated by Django 5.2 on 2025-04-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectmembership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvitation',
            name='role',
            field=models.CharField(choices=[('OWNER', 'OWNER'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'OWNER'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
    ]
