# Generated by Django 5.2 on 2025-04-24 13:57

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='text_rendered'),
        ),
    ]
