# Generated by Django 5.2 on 2025-04-24 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_content_rendered_alter_comment_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='seen_by',
            field=models.ManyToManyField(related_name='comments_seen', to=settings.AUTH_USER_MODEL),
        ),
    ]
