# Generated by Django 5.2 on 2025-04-24 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_seen_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='seen_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments_seen', to=settings.AUTH_USER_MODEL),
        ),
    ]
